server:
  port: 9000
spring:
  application:
    name: "cards"
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "qa"
  rabbitmq:
    host: "localhost"
    port: 5672
    password: "guest"
    username: "guest"

#    for spring boot actuator endpoints to be enabled
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: "cards"
    description: "pbukki Cards Application"
    version: "1.0.0"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka"
