spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to Pbukki cards related prod APIs "
  contactDetails:
    name: "Philip Bukki - QA Lead"
    email: "phil.bukki@gmail.com"
  onCallSupport:
    - +254-798-335-550
    - +254-101-080-341
