services:
  accounts:
    image: "pbukki/accounts:v1"
    container_name: "accounts-ms"
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - pbukki

  loans:
    image: "pbukki/loans:v1"
    container_name: "loans-ms"
    ports:
      - 8040:8040
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - pbukki

  cards:
    image: "pbukki/cards:v1"
    container_name: "cards-ms"
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - pbukki
networks:
  pbukki:
    driver: "bridge"

