spring:
  application:
    name: "gatewayserver"
  config:
    #    import configuration from the config server
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

#    for spring boot actuator endpoints to be enabled
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "pbukki Gateway Server Application"
    version: "1.0.0"





