services:
  network-deploy-service:
    networks:
      -pbukki

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
        memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: qa
