build:
  version: "2.0"

cards:
  message: "Welcome to pbukki cards related prod APIs "
  contactDetails:
    name: "Philip Bukki - Developer"
    email: "phil.bukki@gmail.com"
  onCallSupport:
    - +254-798-335-550
    - +254-101-080-341
