
build:
  version: "2.0"

loans:
  message: "Welcome to Pbukki loans related qa APIs "
  contactDetails:
    name: "Philip Bukki - QA Lead"
    email: "phil.bukki@gmail.com"
  onCallSupport:
    - +254-798-335-550
    - +254-101-080-341
