server:
  port: 8070
spring:
  application:
    name: "accounts"
  profiles:
    active:
      - "qa"
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
   console:
     enabled: true
  rabbitmq:
    host: "localhost"
    port: 5672
    password: "guest"
    username: "guest"

  config:
#    import configuration from the config server

    import: "optional:configserver:http://localhost:8071/"

#    for spring boot actuator endpoints to be enabled
management:
  endpoints:
    web:
      exposure:
        include: "*"






