spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: "native"
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/Philipbukki/microservices-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    username: "guest"
    host: "localhost"
    port: 5672
    password: "guest"
    
server:
  port: 8071

encrypt:
  key: "BFGKFFLHJFONFJ7894RTNFKB"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


