services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  configserver:
    image: "pbukki/configserver:v2"
    container_name: "configserver-ms"
    ports:
      - 8072:8071
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness |grep Up || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    environment:
      SPRING_APPLICATION_NAME: "configserver"

    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "pbukki/accounts:v1"
    container_name: "accounts-ms"
    ports:
      - 8081:8080
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "pbukki/loans:v1"
    container_name: "loans-ms"
    ports:
      - 8041:8040
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "pbukki/cards:v1"
    container_name: "cards-ms"
    ports:
      - 9001:9000
    environment:
      SPRING_APPLICATION_NAME: "cards"

    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  pbukki:
    driver: "bridge"


